### ISSUE TITLE
Docker-compose up not working

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/DataVisPlanner#2]
I get: 

```
ERROR: for celery  Cannot start service celery: oci runtime error: container_linux.go:247: starting container process caused "exec: \"celery\": executable file not found in $PATH"
ERROR: Encountered errors while bringing up the project.
```

**Comment by viktorsmari** [comment]
I noticed celery is missing in the requirements.txt here: https://github.com/fablabbcn/datavizplatform-flask/blob/master/requirements.txt

There might be a problem with using one repo as 2 services (containers). Currently we are using the dataviz-flask as both **celery** and **flask**. Do they each have different requirements.txt ? If they have identical requirements it should be fine, otherwise I guess it needs to be split up to have their own repos, and create another repo for **celery**.

**Comment by rubenlorenzo** [comment]
Add celery to flask with task of proof in /admin/data_task/task_test. The result sees in celery shell. 
Commit:
https://github.com/fablabbcn/datavizplatform-flask/commit/31d98de8919e83924cd334ca46bd88565ed84878
